name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main   # Trigger only on pushes to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest   # GitHub-hosted Ubuntu runner

    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (so we can install requirements before building image)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Python dependencies (requirements.txt)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Log in to Docker Hub (using username + access token as password)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
